"""Initial migration

Revision ID: 139b789a6f88
Revises: 
Create Date: 2025-11-05 15:29:13.479556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '139b789a6f88'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
