"""initial

Revision ID: 3ed58e492ae4
Revises: 79ac4f19e382
Create Date: 2025-11-10 15:58:07.475206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ed58e492ae4'
down_revision = '79ac4f19e382'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draftfaq', schema=None) as batch_op:
        batch_op.add_column(sa.Column('norm_question', sa.String(length=1024), nullable=False))
        batch_op.add_column(sa.Column('modified_by', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('modified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('embedding', sa.LargeBinary(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('pending', 'admin_draft', 'merged', 'rejected', name='draftstatus'),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_draftfaq_norm_question'), ['norm_question'], unique=False)
        batch_op.create_index(batch_op.f('ix_draftfaq_state_name'), ['state_name'], unique=False)
        batch_op.create_unique_constraint('uq_draft_question_state', ['norm_question', 'state_name'])
        batch_op.drop_constraint(batch_op.f('draftfaq_original_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'faq', ['original_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('faq', schema=None) as batch_op:
        batch_op.add_column(sa.Column('norm_question', sa.String(length=1024), nullable=False))
        batch_op.add_column(sa.Column('embedding', sa.LargeBinary(), nullable=True))
        batch_op.alter_column('question',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('reply',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('faq_question_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_question_state'), type_='unique')
        batch_op.create_unique_constraint('uq_question_state', ['norm_question', 'state_name'])
        batch_op.create_index(batch_op.f('ix_faq_norm_question'), ['norm_question'], unique=False)
        batch_op.create_index(batch_op.f('ix_faq_state_name'), ['state_name'], unique=False)

    with op.batch_alter_table('future_issue_tracker', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('future_issue_tracker_related_faq_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('future_issue_tracker_related_draft_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'faq', ['related_faq_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'draftfaq', ['related_draft_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('future_issue_tracker', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('future_issue_tracker_related_draft_id_fkey'), 'draftfaq', ['related_draft_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('future_issue_tracker_related_faq_id_fkey'), 'faq', ['related_faq_id'], ['id'])

    with op.batch_alter_table('faq', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faq_state_name'))
        batch_op.drop_index(batch_op.f('ix_faq_norm_question'))
        batch_op.drop_constraint('uq_question_state', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_question_state'), ['question', 'state_name'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('faq_question_key'), ['question'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('reply',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('question',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
        batch_op.drop_column('embedding')
        batch_op.drop_column('norm_question')

    with op.batch_alter_table('draftfaq', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('draftfaq_original_id_fkey'), 'faq', ['original_id'], ['id'])
        batch_op.drop_constraint('uq_draft_question_state', type_='unique')
        batch_op.drop_index(batch_op.f('ix_draftfaq_state_name'))
        batch_op.drop_index(batch_op.f('ix_draftfaq_norm_question'))
        batch_op.alter_column('status',
               existing_type=sa.Enum('pending', 'admin_draft', 'merged', 'rejected', name='draftstatus'),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('embedding')
        batch_op.drop_column('modified_at')
        batch_op.drop_column('modified_by')
        batch_op.drop_column('norm_question')

    # ### end Alembic commands ###
