"""initial

Revision ID: 79ac4f19e382
Revises: e20a8d5c777e
Create Date: 2025-11-06 14:46:19.525201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79ac4f19e382'
down_revision = 'e20a8d5c777e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('verification_code')
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('verification_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
